### ISSUE TITLE
Don't show pagination if there's only one page

### ISSUE THREAD

**Issue by samwilson** [StydeNet/blade-pagination#4]
It seems unnecessary to show a single page number (of 1) and two arrows, when there's only a single page. Should display be supressed in this circumstance?

**Comment by sileence** [comment]
@samwilson you are right, I'll fix that asap

**Comment by sileence** [comment]
@samwilson done, thank you for reporting the issue.

**Comment by samwilson** [comment]
:) Thanks for the speedy response!
